application: testflask-1315
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2
handlers:
- url: .*  # This regex directs all routes to main.app
  script: main.app
#TODO: Change latest to a specific version.
libraries:
#- name: jinja2
#  version: latest
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "latest"